# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build
      - task: run
  build:
    cmds:
      - go build -o app .
  run:
    cmds:
      - echo -n "HELLO=WORLD" > ./.env
      - defer: rm -f ./.env
      - ./app