# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: show-help
      - task: run
  show-help:
    cmds:
      - go run . help
      - go run . subA help
      - go run . subB help
  run:
    cmds:
      - go run . --val 111
      - go run . subA -v1 222
      - go run . subB -v1 helloworld