# https://taskfile.dev

version: '3'

vars:
  APP: app
  ARCHIVE_FILE: test.7z

tasks:
  default:
    cmds:
      - task: run
  run:
    cmds:
      - 7z a {{.ARCHIVE_FILE}} main.go -bso0 -bsp0
      - defer: rm -f {{.ARCHIVE_FILE}}
      - go build -o {{.APP}}{{.exeExt}} .
      - ./{{.APP}}{{.exeExt}} -in {{.ARCHIVE_FILE}}
      # crc32 コマンドは libarchive-zip-perl パッケージでインストールできる
      - crc32 main.go
      # crc32 コマンドが存在しない場合は gzip コマンドの出力からCRC32を得ることも出来る
      #- gzip -1 -c main.go | tail -c 8 | head -c 4 | hexdump -e '"%08x"'; echo ''
      - wc --bytes main.go
